config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create, :show, :destroy] do
    resources :comments
  end
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, :dependent => :destroy
    has_one_attached :image
    validate :image_presence
    def image_presence
        errors.add(:image, "can't be blank") unless image.attached?
    end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_one_attached :avatar
  has_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
    	@comments = @post.comments.includes(:user)
  	end
	def create
		#@comment = @post.comments.create(comment_params)
		@post = Post.find_by_id(params[:post_id])
		puts comment_params
		@comment = @post.comments.create(comment_params)
		
		if @comment.save
			ActionCable.server.broadcast 'comment_channel',
				content: @comment.content,
				postId: @post.id,
				userUrl:  user_path(@comment.user),
				name: @comment.user.name
			# respond_to :js
			head :ok
		else
			flash.now[:danger] = "error"
		end
	end
	private
    def comment_params
    	params.required(:comment).permit :user_id, :post_id, :content
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def create
      Post.create(post_params)
      redirect_to root_path
    end
    def destroy
      @post = current_user.posts.find(params[:id])
      @post.destroy
      redirect_to user_path(current_user)
    end

    def show
      @post = Post.find(params[:id])
    end
    private
    def post_params
      params.require(:post).permit(:description, :image, :user_id)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user  = User.find(params[:id])
	    @posts = @user.posts.order(created_at: :desc)

	end
	def edit
	    @user=User.find(params[:id])
	end
	def update
      current_user.update(user_params)
      redirect_to current_user
    end
    private
    def user_params
      params.require(:user).permit(:username, :name, :website,
                                   :bio, :email, :phone, :gender, :avatar)
    end

    def destroy
    	user =User.find(params[:id])
    	user.destroy
    	redirect_to user_session, :notice => "Log out sucsseful"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<span class="comment_detail">
    <strong>
        <%= link_to comment.user.name, user_path(comment.user) %>
    </strong>
    <%= comment.content %>
</span>

app/views/comments/_form.html.erb
<%= form_with(model: [ post, post.comments.build ], remote: true, :html => {:class => 'comment_form'}) do |form| %>
	<hr>
  <div class="form-group">
        <%= form.hidden_field :user_id, value: current_user.id %>
    </div>
    <div class="form-group">
		<%= form.hidden_field :post_id, value: post.id %>
    </div>
    <div class="form-group">
        <%= form.text_field :content, class: "form-control", placeholder: "comment ... ", autocomplete: :off %>
    </div>
<% end %>

app/views/home/_post.html.erb
<section class="post">
  <%# User infor area %>
    <%= render 'users/simple_infor', post: post%>
  <%# End user infor area %>

  <%# post content  %>
	<div class="post_content">
		<%= render 'posts/image', post: post%>
    <%= render 'posts/description', post: post%>
  <div>
  <%# end post content  %>
  
  <%# comment area %>
  <div class="comment">
		
    <%# list comment %>
    <div class="comment_list" id = "comment_list_post_<%= post.id %>">
			<% post.comments.each do |comment| %>
    		<%= render 'comments/comment' , comment: comment %>
			<% end %>
		</div>
		<%# end list comment %>

    <%# upload comment %>
    <div class="upload_comment">
			<%= render 'comments/form', post: post %>
		</div>
    <%# end upload comment %>
    						
  <%# end comment	 area %>
</section>

app/views/home/_upload_form.html.erb
<%= form_for Post.new do |f| %>
  <div class="form-group">
    <%= f.text_field :user_id, value: current_user.id, class: 'd-none ' %>
  </div>
  
  <div class="form-group choose_file custom-file ">
    <%= f.file_field :image , class: "custom-file-input" %>
    <label class="custom-file-label" for="customFile">Choose file</label>
  </div>
  <div class="preview">
    <img src="" alt="">
  </div>
  <div class="form-group ">
    <%= f.text_area :description,placeholder: "How are you today  ..." %>
  </div>
  <div class="up_post">
    <%= f.submit 'Create Post', class: 'btn btn-primary ' %>
  </div>
<% end %>

<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      
      $('.preview').css('display', 'block');
      
      reader.onload = function (e) {
        $('.preview img').attr('src', e.target.result);
      }

      reader.readAsDataURL(input.files[0]);
    }
  }

  $(".custom-file-input").on("change", function() {
    var fileName = $(this).val().split("\\").pop();
    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
  });

  $(".custom-file-input").change(function () {
    readURL(this);
  });
</script>

app/views/home/index.html.erb
<div class="homepage">
	<% if user_signed_in? %>
		<div class='form-upload'>
			<%= render 'upload_form' %>
		</div>
		<div class="posts">
			<% @posts.each do |post| %>
				<%# per post %>
				<%# <div class="post"> %>
					<%= render 'post', post: post %>
				<%# </div> %>
				<%# end per post %>
			<% end %>
			<%= paginate @posts %>
		</div>
	<% else %>
		<%# <%= render 'sessions/new', resource: new_user_session_path %>
		<script>
			location.replace("<%= new_user_session_path %>");
		</script>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram.com</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <%# <script src="https://use.fontawesome.com/a5c01e5550.js"></script> %>
    <link rel="shortcut icon" href="https://love2dev.com/img/2000px-instagram_logo_2016svg-2000x2000.png" type="image/x-icon" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="/">
            <%= fa_stacked_icon "camera inverse", base: "circle"%>
            Instagram
          </a>
        </div>
        <div class="m-auto">
          <form class="form-inline search-form">
            <input class="form-control mr-sm-2" type="search" placeholder="@search" aria-label="Search">
          </form>
        </div>
        <div class="user-section">
          <a><i class="fa fa-compass"></i></a>
          <a><i class="fa fa-heart"></i></a>
          <% if user_signed_in? %>
            <a href="<%= user_path(current_user)%>">
              <i class="fa fa-user"></i>
            </a>
          <% else %>
            <a href="<%=new_user_session_path%>">
              <i class="fa fa-sign-in"></i>
            </a>
          <% end %>
        </div>
      </div>
    </nav>

    <!--Main content-->
    <main class="container" style="min-height: 500px;">
      <%= yield %>
    </main>

    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>ABOUT US
          </li>
          <li>SUPPORT</li>
          <li>PRESS</li>
          <li>API</li>
          <li>JOBS</li>
          <li>PRIVACY</li>
          <li>TERMS</li>
          <li>DIRECTORY</li>
          <li>PROFILES</li>
          <li>HASHTAGS</li>
          <li>LANGUAGE</li>
        </ul>
        <p> © 2019 WEB PROJECT 20191 </p>
      </nav>
    </footer>
  </body>
</html

app/views/posts/_description.html.erb
<div class="description">
	<strong>
		<%= post.user.name%>
	</strong>
	<%= post.description %>
</div>

app/views/posts/_image.html.erb
<div class="image">
    <div class="image_area">
		<%= link_to post_path(post) do %>
		  <%= image_tag post.image, class: 'main-image' %>
		<% end %>
    </div>
    <div class = "like_area">
        <div class= "core-sprite love hide-text" >
        </div>
        
        <div class= "core-sprite comment_icon hide-text ">
        </div>

        <div class="core-sprite bookmark hide-text"> </div>
    </div>
</div>
<hr class="style1">

app/views/posts/show.html.erb
<div class="post-show row">
  
  <div class="col-md-8">
    <%=image_tag @post.image, class: 'image' %>
  </div>

  <div class="col-md-4">
    
    <%# User infor area %>
    <%= render 'users/simple_infor', post: @post%>
    <%# End user infor area %>
    
    <%# description area %>
    <%# <div class="description"> %>
      <%= render partial: "description", locals: {post: @post} %>
    <%# </div> %>
    <%# end description area %>

    <div class="comment">
      <%# comment list %>
      <div class="comment_list" id = "comment_list_post_<%= @post.id %>">
			  <% @post.comments.each do |comment| %>
    		  <%= render 'comments/comment' , comment: comment %>
			  <% end %>
		  </div>
      <%# end comment list %>

      <%# upload comment %>
      <div class="upload_comment">
			  <%= render 'comments/form', post: @post %>
		  </div>
      <%# end upload comment %>
    </div>
  
  </div>

</div>

app/views/users/_simple_infor.html.erb
<div class="user">
    <%= link_to user_path(post.user) do %>
        <div class="avatar">
	        <% if post.user.avatar.attached? %>
                <%= image_tag post.user.avatar %>
            <% else%>
		        <img src="https://static.thenounproject.com/png/17241-200.png" alt="">
	        <% end %>
	    </div>
        <span>
            <%= link_to post.user.name, user_path(post.user), class: 'username' %>
        </span>
    <% end %>
    <% if current_user.posts.exists?(post.id) %>
        <%= link_to  post_path(post), class:"delete_btn ml-auto", method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash fa-lg"></i>
        <% end %>
    <% end %>
</div>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
      <a class="nav-link" data-toggle="pill">Change Password</a>
      <a class="nav-link" data-toggle="pill">Authorized Applications</a>
      <a class="nav-link" data-toggle="pill">Email and SMS</a>
      <a class="nav-link" data-toggle="pill">Manage Contacts</a>
      <a class="nav-link" data-toggle="pill">Privacy and Security</a>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
        DCM RAILS
        <div class="form-group row">
          <div class="col-sm-3 col-form-label">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: 'avatar' %>
            <%end %>
          </div>
          <div class="col-sm-9">
            <p class="username"><%=current_user.username %></p>
            <a class="change-photo" href="">Change Profile Photo</a>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :avatar, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.file_field :avatar, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :name, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :username, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :website, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :website, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_area :bio, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :email, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :phone, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :phone, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :gender, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :gender, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-3">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Submit", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar %>
        <%end %>
      </div>
    </div>
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= @user.username %></h2>
        <% if @user == current_user %>
          <a class="edit-profile" href="<%= edit_user_path(@user) %>">
            <button>Edit Profile</button>
          </a>
          <a class="log-out" href="<%=destroy_user_session_path%>">
            <i class="fa fa-sign_in"></i>
            <button>Log Out</button>
          </a>
        <% end %>
      </div>
      <ul class="posts">
        <li><span><%= @posts.count %></span> posts</li>
        <li><span>100</span> followers</li>
        <li><span>300</span> following</li>
      </ul>
      <h2 class="name"><%=@user.name %></h2>
      <%=link_to @user.website, @user.website, class: 'website' %>
    </div>
  </div>

  <div class="user-tabs">
    <a class="tab active" href="">
      <i class="fa fa-th"></i>
      POSTS
    </a>
    <a class="tab" href="">
      <i class="fa fa-tv"></i>
      IGTV
    </a>
    <a class="tab" href="">
      <i class="fa fa-bookmark"></i>
      SAVED
    </a>
    <a class="tab" href="">
      <i class="fa fa-tag"></i>
      TAGGED
    </a>
  </div>

  <div class="user-images">
    <% @posts.each do |post|%>
      <div class="wrapper">
        <%=link_to post_path(post) do %>
          <%=image_tag post.image %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>